apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-spatial-pvc
  namespace: mdoner-disaster-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: mdoner-disaster-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
